mystr ="this is nothing but Something"
print(mystr)
print("Index of String : ",mystr[6])
print("Index of String : ",mystr[0:4])
print("Lenght of String : ",len(mystr))
print("Index of String : ",mystr[0:28:3])
print("Index of String : ",mystr[::-1])
print("Index of String : ",mystr[-10:-1])
print(mystr.isalpha())
print(mystr.isalnum())
print(mystr.endswith("Something"))
print(mystr.count('i'))
print(mystr.capitalize())
print(mystr.encode())
print(mystr.find("but"))
print(mystr.upper())
print(mystr.replace("nothing","much More"))
print(mystr.lower())


