import random
# random_number = random.randint(0,10)
rand = random.random()*100
print("The random number generated by system is :",rand)

lisst = ["shabbir hussain","aryan khan parwana", "sk bumal khan","shakir aryan khan"]
choice = random.choice(lisst)
print("The random Choice generated by system is :",choice)
